//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFSU2CH {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFSU2CH.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        internal static string authError {
            get {
                return ResourceManager.GetString("authError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный GlobalB.lzc! Невозможно починить, попробуйте поспрашивать у друзей или поискать в интернете. Оригинальный файл должен весить больше 7 мб!.
        /// </summary>
        internal static string badGlobalb {
            get {
                return ResourceManager.GetString("badGlobalb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить настройку для текущей машины....
        /// </summary>
        internal static string carFileOpen {
            get {
                return ResourceManager.GetString("carFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке файла.
        /// </summary>
        internal static string fileLoadError {
            get {
                return ResourceManager.GetString("fileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл успешно загружен!.
        /// </summary>
        internal static string fileLoadOk {
            get {
                return ResourceManager.GetString("fileLoadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран файл настроек! Выберите файл, нажав пункт Меню -&gt; Открыть файл настроек...!.
        /// </summary>
        internal static string fileNotSelected {
            get {
                return ResourceManager.GetString("fileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас был неверный файл GlobalB.lzc! Мы исправили его, теперь можно пользоваться программой! =).
        /// </summary>
        internal static string globalbRepaired {
            get {
                return ResourceManager.GetString("globalbRepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на успешно загружен!.
        /// </summary>
        internal static string loaded {
            get {
                return ResourceManager.GetString("loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь выберите машину..
        /// </summary>
        internal static string loadedThenSelectCar {
            get {
                return ResourceManager.GetString("loadedThenSelectCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нечего сохранять!.
        /// </summary>
        internal static string nothingToSave {
            get {
                return ResourceManager.GetString("nothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NFSU2 GlobalB.lzc ( GLOBAL\GlobalB.lzc )|GlobalB.lzc.
        /// </summary>
        internal static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сохранен!.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения файла!.
        /// </summary>
        internal static string saveError {
            get {
                return ResourceManager.GetString("saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машины NFSU2CH (*.car)|*.car.
        /// </summary>
        internal static string saveFileDialogFilter {
            get {
                return ResourceManager.GetString("saveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить настройки машины....
        /// </summary>
        internal static string saveFileDialogTitle {
            get {
                return ResourceManager.GetString("saveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл сохранен!.
        /// </summary>
        internal static string saveOk {
            get {
                return ResourceManager.GetString("saveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите машину...
        /// </summary>
        internal static string selectCar {
            get {
                return ResourceManager.GetString("selectCar", resourceCulture);
            }
        }
    }
}
